### ISSUE TITLE
Error when try to install -- prefix auth

### ISSUE THREAD

**Issue by diorz38** [ooade/vuex-examples#19]
Error when try to install -- prefix auth
step to produce:
```
npm --prefix auth install auth
npm --prefix auth run dev
```
```
ERROR in ./src/main.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
BrowserslistError: [BABEL] D:\DOCS\Git\vuex-examples\auth\src\main.js: Unknown browser query `basedir=$(dirname "$(echo "$0" | sed -e 's`. Maybe you are using old Browserslist or made typo in query. (While processing: "D:\\DOCS\\Git\\vuex-examples\\auth\\node_modules\\@babel\\preset-env\\lib\\index.js")
    at unknownQuery (D:\DOCS\Git\vuex-examples\auth\node_modules\browserslist\index.js:118:10)
    at D:\DOCS\Git\vuex-examples\auth\node_modules\browserslist\index.js:157:11
    at Array.reduce (<anonymous>)
    at resolve (D:\DOCS\Git\vuex-examples\auth\node_modules\browserslist\index.js:125:18)
    at browserslist (D:\DOCS\Git\vuex-examples\auth\node_modules\browserslist\index.js:222:16)
    at getTargets (D:\DOCS\Git\vuex-examples\auth\node_modules\@babel\preset-env\lib\targets-parser.js:183:50)
    at _default (D:\DOCS\Git\vuex-examples\auth\node_modules\@babel\preset-env\lib\index.js:187:46)
    at D:\DOCS\Git\vuex-examples\auth\node_modules\@babel\helper-plugin-utils\lib\index.js:19:12
    at loadDescriptor (D:\DOCS\Git\vuex-examples\auth\node_modules\@babel\core\lib\config\full.js:165:14)
    at cachedFunction (D:\DOCS\Git\vuex-examples\auth\node_modules\@babel\core\lib\config\caching.js:33:19)
    at loadPresetDescriptor (D:\DOCS\Git\vuex-examples\auth\node_modules\@babel\core\lib\config\full.js:235:63)
    at config.presets.reduce (D:\DOCS\Git\vuex-examples\auth\node_modules\@babel\core\lib\config\full.js:77:21)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (D:\DOCS\Git\vuex-examples\auth\node_modules\@babel\core\lib\config\full.js:74:38)
    at loadFullConfig (D:\DOCS\Git\vuex-examples\auth\node_modules\@babel\core\lib\config\full.js:108:6)
    at process.nextTick (D:\DOCS\Git\vuex-examples\auth\node_modules\@babel\core\lib\transform.js:28:33)
```

**Comment by ooade** [comment]
Hi @diorz38. An auth package would have been installed if it existed using the first command.
What you should have done:
```sh
npm --prefix auth install
npm --prefix auth run dev
```

Tho, I don't see any correlation with that to the error. Can I get more details?
OS:
Browser:
